// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZiuPWtkcYOMNZW58y_HUlLnGJ81iv8Lk',
    appId: '1:968788665912:web:0b765831cbadb90b2928cd',
    messagingSenderId: '968788665912',
    projectId: 'app-savon',
    authDomain: 'app-savon.firebaseapp.com',
    storageBucket: 'app-savon.appspot.com',
    measurementId: 'G-K0BXRCK2J6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiQjuehuhStrpNk72YG6oPX-u1GFtWdk8',
    appId: '1:968788665912:android:1c28af4ab92f0f272928cd',
    messagingSenderId: '968788665912',
    projectId: 'app-savon',
    storageBucket: 'app-savon.appspot.com',
  );
}
